### ISSUE TITLE
After issuing a color change, following commands fail to do anything.

### ISSUE THREAD

**Issue by thevik** [KsenijaS/krakenx#10]
Arch Linux 4.17.2

After a fresh restart, with the LED's of my kraken x62 off:

colctl -m solid -c0 50,0,90  successfully changes the LED's from black to purple

immediately after I run:

colctl -m solid -c0 0,0,0 to change the LED's back to black but nothing happens.

no other colctl commands seem to work until I restart again.

**Comment by willkill07** [comment]
I also report the same issue.

kernel version: 4.17.2-1-ARCH
Hardware: Kraken x62

**Comment by jonasmalacofilho** [comment]
I can reproduce this as well.

**Comment by jneumaier** [comment]
I guess this has been fixed accidentally. Works for me. Please verify.

**Comment by jonasmalacofilho** [comment]
I can still reproduce this after a fresh boot, at least on Linux.

Could this maybe be related to detaching the kernel driver but never reattaching it?

**Comment by jneumaier** [comment]
Thanks @jonasmalacofilho I merged the pull request #23 but only had time to verify everything works on Windows.
@thevik @willkill07 If you have the time, you are welcome to verfiy the fix on Linux. Otherwise I will just trust jonasmalacofilho's expertise and close the issue in a few days :-)

**Comment by thevik** [comment]
Verified on Linux. Thanks for the fix! @jneumaier

**Comment by jneumaier** [comment]
@thevik Perfect, thanks!
